apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

resources:
- ../../base

namespace: default
images:
- name: 576066064056.dkr.ecr.ap-northeast-2.amazonaws.com/yieon-kubernetes-secrets-updater-practice
  newTag: 0.0.1