apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-secrets-updater-practice-deployment
  namespace: kubernetes-secrets-updater-practice
  labels:
    app: kubernetes-secrets-updater-practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-secrets-updater-practice
  template:
    metadata:
      labels:
        app: kubernetes-secrets-updater-practice
    spec:
      containers:
        - name: kubernetes-secrets-updater-practice
          image: 576066064056.dkr.ecr.ap-northeast-2.amazonaws.com/yieon-kubernetes-secrets-updater-practice:IMAGE_TAG
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: kubernetes-secrets-updater-practice
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 300m
          env:
            - name: aws_access_key_id
              valueFrom:
                configMapKeyRef:
                  name: kube-env
                  key: aws_access_key_id
            - name: aws_secret_access_key
              valueFrom:
                configMapKeyRef:
                  name: kube-env
                  key: aws_secret_access_key
            - name: kube_config
              valueFrom:
                configMapKeyRef:
                  name: kube-env
                  key: kube_config
      tolerations:
        - effect: NoSchedule
          key: subnettype
          operator: Equal
          value: private
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: subnettype
                    operator: In
                    values:
                      - private