apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kubernetes-secrets-updater-practice-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: kubernetes-secrets-updater-practice