apiVersion: v1
kind: Service
metadata:
  name: kubernetes-secrets-updater-practice
  namespace: default
  labels:
    app: kubernetes-secrets-updater-practice
spec:
  selector:
    app: kubernetes-secrets-updater-practice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000